version: "3.8"

services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.61  # Thay đổi địa chỉ IP cho phù hợp
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    volumes:
      - ./kafka-data:/var/lib/kafka/data

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"