// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: bio/bio.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BioService_SayHi_FullMethodName = "/bio.BioService/SayHi"
)

// BioServiceClient is the client API for BioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BioServiceClient interface {
	// sends hi
	SayHi(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HelloReply, error)
}

type bioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBioServiceClient(cc grpc.ClientConnInterface) BioServiceClient {
	return &bioServiceClient{cc}
}

func (c *bioServiceClient) SayHi(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, BioService_SayHi_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BioServiceServer is the server API for BioService service.
// All implementations must embed UnimplementedBioServiceServer
// for forward compatibility
type BioServiceServer interface {
	// sends hi
	SayHi(context.Context, *emptypb.Empty) (*HelloReply, error)
	mustEmbedUnimplementedBioServiceServer()
}

// UnimplementedBioServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBioServiceServer struct {
}

func (UnimplementedBioServiceServer) SayHi(context.Context, *emptypb.Empty) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHi not implemented")
}
func (UnimplementedBioServiceServer) mustEmbedUnimplementedBioServiceServer() {}

// UnsafeBioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BioServiceServer will
// result in compilation errors.
type UnsafeBioServiceServer interface {
	mustEmbedUnimplementedBioServiceServer()
}

func RegisterBioServiceServer(s grpc.ServiceRegistrar, srv BioServiceServer) {
	s.RegisterService(&BioService_ServiceDesc, srv)
}

func _BioService_SayHi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BioServiceServer).SayHi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BioService_SayHi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BioServiceServer).SayHi(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BioService_ServiceDesc is the grpc.ServiceDesc for BioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bio.BioService",
	HandlerType: (*BioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHi",
			Handler:    _BioService_SayHi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bio/bio.proto",
}
